### ISSUE TITLE
To list for training 

### ISSUE THREAD

**Issue by likelet** [likelet/multiexseq#1]
# 1. Stage one for using github  
- [ ] install git 
- [ ] git initialize 
- [ ] first commit 
- [ ] create a github account 
- [ ] add account into project `contact me `
- [ ] created a new branch with local names 
- [ ] add `yourname.conf` file under `conf` folder
- [ ]  make a PR (pull request )

**Comment by lizheng141026** [comment]
- [√]  install git
- [√ ] git initialize
- [√ ] first commit
- [√] create a github account
- [√]  add account into project contact me
- [√] created a new branch with local names
- [√ ] add yourname.conf file under conf folder
- [√] make a PR (pull request )

**Comment by Ninomoriaty** [comment]
- [x]  install git
- [x]   git initialize
- [x]   first commit
- [x]   create a github account
- [x]   add account into project contact me
- [x]   created a new branch with local names
- [x]   add yourname.conf file under conf folder
- [x]   make a PR (pull request )

**Comment by ZIWEI-WONG** [comment]
- [ ]   install git
- [ ]   git initialize
- [ ]   first commit
- [ ]   create a github account
- [ ]   add account into project contact me
- [ ]   created a new branch with local names
- [ ]   add yourname.conf file under conf folder
- [ ]   make a PR (pull request )

**Comment by chenjy327** [comment]
- [ ] install git
- [ ] git initialize
- [ ] first commit
- [ ] create a github account
- [ ] add account into project contact me
- [ ] created a new branch with local names
- [ ] add yourname.conf file under conf folder
- [ ] make a PR (pull request )

**Comment by Wangxin555** [comment]
- [ ]  install git
- [ ] git initialize
- [ ] first commit
- [ ] create a github account
- [ ] add account into project contact me 
- [ ] created a new branch with local names
- [ ] add yourname.conf file under conf folder
- [ ] make a PR (pull request )

**Comment by LiuJie1117** [comment]
- [ ] install git

- [ ]  git initialize

- [ ] first commit

- [ ] create a github account

- [ ] add account into project contact me

- [ ]  created a new branch with local names

- [ ]  add yourname.conf file under conf folder

- [ ] make a PR (pull request )
